modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "RealityLink"
authors = "idkana"
description = '''
A neat in-game chat interacting API with server-side l10n support, suitable for chatbots.
'''
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"
