modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "reallink"
version = "${version}"
displayName = "RealityLink"
authors = "idkana"
description = """
A neat in-game chat interacting API with server-side l10n support, suitable for chatbots.
"""
displayTest = "IGNORE_SERVER_VERSION"

[[mixins]]
config = "reallink.mixins.json"

[[dependencies.reallink]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reallink]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
