modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "reallink"
version = "1.21-0.2.0"
displayName = "RealityLink"
description = """
A neat in-game chat interacting API with server-side l10n support, suitable for chatbots.
"""
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.reallink]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reallink]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "reallink.mixins.json"
