modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "reallink"
version = "1.18.2-0.2.0"
displayName = "RealityLink"
description = """
A neat in-game chat interacting API with server-side l10n support, suitable for chatbots.
"""
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.reallink]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reallink]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"
