[versions]
minecraft = "1.21"
architectury-api = "13.0.2"
fabric-loader = "0.16.5"
fabric-api = "0.102.0+1.21"
neoforge = "21.0.167"
parchment-mappings = "2024.07.28"

grpc-java = "1.66.0"
protoc = "3.25.3" # the same as the protoc version used in grpc-java
tomcat-annotations-api = "6.0.53"
protobuf-plugin = "0.9.4"

architectury-plugin = "3.4.159"
architectury-loom = "1.7.413"
shadow = "8.3.2"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
architectury-api = { module = "dev.architectury:architectury", version.ref = "architectury-api" }
architectury-api-neoforge = { module = "dev.architectury:architectury-neoforge", version.ref = "architectury-api" }
architectury-api-fabric = { module = "dev.architectury:architectury-fabric", version.ref = "architectury-api" }
parchment-mappings = { module = "org.parchmentmc.data:parchment-1.21", version.ref = "parchment-mappings" }

# grpc
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc-java" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc-java" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc-java" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }
protoc-gen-grpc-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc-java" }
tomcat-annotations-api = { module = "org.apache.tomcat:annotations-api", version.ref = "tomcat-annotations-api" }

# plugins as libraries, used in convetion plugins
architectury-plugin = { module = "architectury-plugin:architectury-plugin.gradle.plugin", version.ref = "architectury-plugin" }
architectury-loom = { module = "dev.architectury.loom:dev.architectury.loom.gradle.plugin", version.ref = "architectury-loom" }
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

[bundles]

[plugins]
architectury-plugin = { id = "architectury-plugin", version.ref = "architectury-plugin" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
