modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "reallink"
version = "${version}"
displayName = "RealityLink"
description = """
A neat in-game chat interacting API with server-side l10n support, suitable for chatbots.
"""
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.reallink]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reallink]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
