modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "realcomm"
version = "${version}"
displayName = "Reality Communication"
authors = "idkana"
description = '''
A neat in-game chat interacting API with server-side l10n support, suitable for chatbots.
'''
#logoFile = ""
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.realcomm]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.realcomm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "realcomm.mixins.json"
