modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "realcomm"
version = "${version}"
displayName = "Reality Communication"
authors = "Me!"
description = '''
Communication between player in the game and the reality.
'''
#logoFile = ""

[[dependencies.realcomm]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.realcomm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.realcomm]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

#[[mixins]]
#config = "realcomm.mixins.json"
